version: "3.8"

services:
   # Your existing services here

   # Redis for Bull queues
   redis:
      image: redis:alpine
      ports:
         - "6379:6379"
      volumes:
         - redis-data:/data
      command: redis-server --appendonly yes
      restart: unless-stopped
      healthcheck:
         test: ["CMD", "redis-cli", "ping"]
         interval: 10s
         timeout: 5s
         retries: 3

   # Optional Redis UI
   redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
         - REDIS_HOSTS=local:redis:6379
      ports:
         - "8081:8081"
      depends_on:
         - redis
      restart: unless-stopped

volumes:
   redis-data:
