[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc = "0.8.28"
force = false
optimizer = true
via_ir = true
optimizer_runs = 200

# Remappings
remappings = [
   "@libraries/=src/libraries",
   "@simple-tasks/=src/simple-tasks/",
   "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
   "@chainlink/contracts/=lib/chainlink/contracts/",
   "@script/=script/",
   "@src/=src/",
   "@test/=test/",
   "@abdk-libraries-solidity/=lib/abdk-libraries-solidity/",
]

# File system permissions
fs_permissions = [
   { access = "read", path = "./broadcast" },
   { access = "read", path = "./reports" },
]

# Etherscan verification
[profile.default.etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# Formatter settings
[fmt]
line_length = 120
tab_width = 3
bracket_spacing = true
indent_width = 3
indent_type = "tabs"

# Model checker
[profile.default.model_checker]
contracts = { "src/TokenVesting.sol" = ["TokenVesting"] }
