/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GreetingInterface extends Interface {
  getFunction(
    nameOrSignature: "getGreeting" | "greeting" | "owner" | "setGreeting"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GreetingSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "getGreeting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "greeting", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "setGreeting", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "greeting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGreeting",
    data: BytesLike
  ): Result;
}

export namespace GreetingSetEvent {
  export type InputTuple = [_newGreeting: string, owner: AddressLike];
  export type OutputTuple = [_newGreeting: string, owner: string];
  export interface OutputObject {
    _newGreeting: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Greeting extends BaseContract {
  connect(runner?: ContractRunner | null): Greeting;
  waitForDeployment(): Promise<this>;

  interface: GreetingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGreeting: TypedContractMethod<[], [string], "view">;

  greeting: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setGreeting: TypedContractMethod<
    [_newGreeting: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGreeting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "greeting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGreeting"
  ): TypedContractMethod<[_newGreeting: string], [void], "nonpayable">;

  getEvent(
    key: "GreetingSet"
  ): TypedContractEvent<
    GreetingSetEvent.InputTuple,
    GreetingSetEvent.OutputTuple,
    GreetingSetEvent.OutputObject
  >;

  filters: {
    "GreetingSet(string,address)": TypedContractEvent<
      GreetingSetEvent.InputTuple,
      GreetingSetEvent.OutputTuple,
      GreetingSetEvent.OutputObject
    >;
    GreetingSet: TypedContractEvent<
      GreetingSetEvent.InputTuple,
      GreetingSetEvent.OutputTuple,
      GreetingSetEvent.OutputObject
    >;
  };
}
