/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSignatureWallet } from "./MultiSignatureWallet";
export * as factories from "./factories";
export { MultiSignatureWallet__factory } from "./factories/MultiSignatureWallet__factory";
