/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SecretMessage } from "./SecretMessage";
export * as factories from "./factories";
export { SecretMessage__factory } from "./factories/SecretMessage__factory";
