/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MultiSignatureWallet {
  export type ProposedAdminStruct = {
    newAdmin: AddressLike;
    approvals: BigNumberish;
    disapprovals: BigNumberish;
    isActive: boolean;
  };

  export type ProposedAdminStructOutput = [
    newAdmin: string,
    approvals: bigint,
    disapprovals: bigint,
    isActive: boolean
  ] & {
    newAdmin: string;
    approvals: bigint;
    disapprovals: bigint;
    isActive: boolean;
  };

  export type TransactionStruct = {
    txHash: BytesLike;
    txIndex: BigNumberish;
    from: AddressLike;
    to: AddressLike;
    amount: BigNumberish;
    data: BytesLike;
    executed: boolean;
    confirmations: BigNumberish;
    confirmers: AddressLike[];
    timestamp: BigNumberish;
  };

  export type TransactionStructOutput = [
    txHash: string,
    txIndex: bigint,
    from: string,
    to: string,
    amount: bigint,
    data: string,
    executed: boolean,
    confirmations: bigint,
    confirmers: string[],
    timestamp: bigint
  ] & {
    txHash: string;
    txIndex: bigint;
    from: string;
    to: string;
    amount: bigint;
    data: string;
    executed: boolean;
    confirmations: bigint;
    confirmers: string[];
    timestamp: bigint;
  };
}

export interface MultiSignatureWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN"
      | "REQUIRED_SIGNATURES"
      | "addNewOwner"
      | "addressToIndex"
      | "adminChangeConfirmations"
      | "approveProposedAdmin"
      | "changeRequiredSignatures"
      | "checkHasVoted"
      | "checkIsOwner"
      | "confirmTransaction"
      | "confirmedTransactions"
      | "disApproveNewAdmin"
      | "executeTransaction"
      | "getBalace"
      | "getCurrentAdminDetails"
      | "getOwners"
      | "getPropsedAdminDetails"
      | "getRequiredSignatures"
      | "getTransationDetails"
      | "getUserTransactions"
      | "owners"
      | "proposeNewAdmin"
      | "proposedAdmin"
      | "removeOwner"
      | "revokeTransaction"
      | "submitTransaction"
      | "transactionAddresses"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChangeApproved"
      | "AdminChangeDisapproved"
      | "AdminChangeProposed"
      | "OwnerAdded"
      | "OwnerRemoved"
      | "TransactionConfrimed"
      | "TransactionExecuted"
      | "TransactionRevoked"
      | "TransactionSubmitted"
      | "VotedAdminChange"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ADMIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REQUIRED_SIGNATURES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addNewOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminChangeConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveProposedAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeRequiredSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkHasVoted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmedTransactions",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disApproveNewAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getBalace", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentAdminDetails",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPropsedAdminDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredSignatures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransationDetails",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeNewAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposedAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTransaction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REQUIRED_SIGNATURES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addNewOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminChangeConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveProposedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRequiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkHasVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmedTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disApproveNewAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentAdminDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPropsedAdminDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransationDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeNewAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace AdminChangeApprovedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminChangeDisapprovedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminChangeProposedEvent {
  export type InputTuple = [proposer: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [proposer: string, newAdmin: string];
  export interface OutputObject {
    proposer: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerAddedEvent {
  export type InputTuple = [owner: AddressLike, ownerIndex: BigNumberish];
  export type OutputTuple = [owner: string, ownerIndex: bigint];
  export interface OutputObject {
    owner: string;
    ownerIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerRemovedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionConfrimedEvent {
  export type InputTuple = [
    txIndex: BigNumberish,
    txHash: BytesLike,
    owner: AddressLike
  ];
  export type OutputTuple = [txIndex: bigint, txHash: string, owner: string];
  export interface OutputObject {
    txIndex: bigint;
    txHash: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [txIndex: BigNumberish, txHash: BytesLike];
  export type OutputTuple = [txIndex: bigint, txHash: string];
  export interface OutputObject {
    txIndex: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionRevokedEvent {
  export type InputTuple = [
    txIndex: BigNumberish,
    txHash: BytesLike,
    owner: AddressLike
  ];
  export type OutputTuple = [txIndex: bigint, txHash: string, owner: string];
  export interface OutputObject {
    txIndex: bigint;
    txHash: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionSubmittedEvent {
  export type InputTuple = [
    txIndex: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    txIndex: bigint,
    from: string,
    to: string,
    amount: bigint,
    data: string
  ];
  export interface OutputObject {
    txIndex: bigint;
    from: string;
    to: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedAdminChangeEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSignatureWallet extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSignatureWallet;
  waitForDeployment(): Promise<this>;

  interface: MultiSignatureWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN: TypedContractMethod<[], [string], "view">;

  REQUIRED_SIGNATURES: TypedContractMethod<[], [bigint], "view">;

  addNewOwner: TypedContractMethod<
    [_newOwner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  addressToIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  adminChangeConfirmations: TypedContractMethod<[], [bigint], "view">;

  approveProposedAdmin: TypedContractMethod<
    [],
    [MultiSignatureWallet.ProposedAdminStructOutput],
    "nonpayable"
  >;

  changeRequiredSignatures: TypedContractMethod<
    [_confirmations: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkHasVoted: TypedContractMethod<[], [boolean], "view">;

  checkIsOwner: TypedContractMethod<[_owner: AddressLike], [boolean], "view">;

  confirmTransaction: TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;

  confirmedTransactions: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  disApproveNewAdmin: TypedContractMethod<[], [void], "nonpayable">;

  executeTransaction: TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getBalace: TypedContractMethod<[], [bigint], "view">;

  getCurrentAdminDetails: TypedContractMethod<[], [string], "view">;

  getOwners: TypedContractMethod<[], [string[]], "view">;

  getPropsedAdminDetails: TypedContractMethod<
    [],
    [MultiSignatureWallet.ProposedAdminStructOutput],
    "view"
  >;

  getRequiredSignatures: TypedContractMethod<[], [bigint], "view">;

  getTransationDetails: TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "view"
  >;

  getUserTransactions: TypedContractMethod<
    [],
    [MultiSignatureWallet.TransactionStructOutput[]],
    "view"
  >;

  owners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  proposeNewAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [string],
    "nonpayable"
  >;

  proposedAdmin: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, boolean] & {
        newAdmin: string;
        approvals: bigint;
        disapprovals: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  removeOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  revokeTransaction: TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;

  submitTransaction: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _data: BytesLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;

  transactionAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  transactions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        txHash: string;
        txIndex: bigint;
        from: string;
        to: string;
        amount: bigint;
        data: string;
        executed: boolean;
        confirmations: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REQUIRED_SIGNATURES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addNewOwner"
  ): TypedContractMethod<[_newOwner: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "addressToIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminChangeConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveProposedAdmin"
  ): TypedContractMethod<
    [],
    [MultiSignatureWallet.ProposedAdminStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeRequiredSignatures"
  ): TypedContractMethod<
    [_confirmations: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkHasVoted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsOwner"
  ): TypedContractMethod<[_owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confirmTransaction"
  ): TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmedTransactions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "disApproveNewAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalace"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentAdminDetails"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPropsedAdminDetails"
  ): TypedContractMethod<
    [],
    [MultiSignatureWallet.ProposedAdminStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequiredSignatures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransationDetails"
  ): TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTransactions"
  ): TypedContractMethod<
    [],
    [MultiSignatureWallet.TransactionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proposeNewAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "proposedAdmin"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, boolean] & {
        newAdmin: string;
        approvals: bigint;
        disapprovals: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeTransaction"
  ): TypedContractMethod<
    [_txIndex: BigNumberish, _from: AddressLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitTransaction"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _data: BytesLike],
    [MultiSignatureWallet.TransactionStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactionAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        txHash: string;
        txIndex: bigint;
        from: string;
        to: string;
        amount: bigint;
        data: string;
        executed: boolean;
        confirmations: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AdminChangeApproved"
  ): TypedContractEvent<
    AdminChangeApprovedEvent.InputTuple,
    AdminChangeApprovedEvent.OutputTuple,
    AdminChangeApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AdminChangeDisapproved"
  ): TypedContractEvent<
    AdminChangeDisapprovedEvent.InputTuple,
    AdminChangeDisapprovedEvent.OutputTuple,
    AdminChangeDisapprovedEvent.OutputObject
  >;
  getEvent(
    key: "AdminChangeProposed"
  ): TypedContractEvent<
    AdminChangeProposedEvent.InputTuple,
    AdminChangeProposedEvent.OutputTuple,
    AdminChangeProposedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerAdded"
  ): TypedContractEvent<
    OwnerAddedEvent.InputTuple,
    OwnerAddedEvent.OutputTuple,
    OwnerAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerRemoved"
  ): TypedContractEvent<
    OwnerRemovedEvent.InputTuple,
    OwnerRemovedEvent.OutputTuple,
    OwnerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionConfrimed"
  ): TypedContractEvent<
    TransactionConfrimedEvent.InputTuple,
    TransactionConfrimedEvent.OutputTuple,
    TransactionConfrimedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionRevoked"
  ): TypedContractEvent<
    TransactionRevokedEvent.InputTuple,
    TransactionRevokedEvent.OutputTuple,
    TransactionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionSubmitted"
  ): TypedContractEvent<
    TransactionSubmittedEvent.InputTuple,
    TransactionSubmittedEvent.OutputTuple,
    TransactionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VotedAdminChange"
  ): TypedContractEvent<
    VotedAdminChangeEvent.InputTuple,
    VotedAdminChangeEvent.OutputTuple,
    VotedAdminChangeEvent.OutputObject
  >;

  filters: {
    "AdminChangeApproved(address,address)": TypedContractEvent<
      AdminChangeApprovedEvent.InputTuple,
      AdminChangeApprovedEvent.OutputTuple,
      AdminChangeApprovedEvent.OutputObject
    >;
    AdminChangeApproved: TypedContractEvent<
      AdminChangeApprovedEvent.InputTuple,
      AdminChangeApprovedEvent.OutputTuple,
      AdminChangeApprovedEvent.OutputObject
    >;

    "AdminChangeDisapproved(address,address)": TypedContractEvent<
      AdminChangeDisapprovedEvent.InputTuple,
      AdminChangeDisapprovedEvent.OutputTuple,
      AdminChangeDisapprovedEvent.OutputObject
    >;
    AdminChangeDisapproved: TypedContractEvent<
      AdminChangeDisapprovedEvent.InputTuple,
      AdminChangeDisapprovedEvent.OutputTuple,
      AdminChangeDisapprovedEvent.OutputObject
    >;

    "AdminChangeProposed(address,address)": TypedContractEvent<
      AdminChangeProposedEvent.InputTuple,
      AdminChangeProposedEvent.OutputTuple,
      AdminChangeProposedEvent.OutputObject
    >;
    AdminChangeProposed: TypedContractEvent<
      AdminChangeProposedEvent.InputTuple,
      AdminChangeProposedEvent.OutputTuple,
      AdminChangeProposedEvent.OutputObject
    >;

    "OwnerAdded(address,uint256)": TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;
    OwnerAdded: TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;

    "OwnerRemoved(address)": TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;
    OwnerRemoved: TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;

    "TransactionConfrimed(uint256,bytes32,address)": TypedContractEvent<
      TransactionConfrimedEvent.InputTuple,
      TransactionConfrimedEvent.OutputTuple,
      TransactionConfrimedEvent.OutputObject
    >;
    TransactionConfrimed: TypedContractEvent<
      TransactionConfrimedEvent.InputTuple,
      TransactionConfrimedEvent.OutputTuple,
      TransactionConfrimedEvent.OutputObject
    >;

    "TransactionExecuted(uint256,bytes32)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionRevoked(uint256,bytes32,address)": TypedContractEvent<
      TransactionRevokedEvent.InputTuple,
      TransactionRevokedEvent.OutputTuple,
      TransactionRevokedEvent.OutputObject
    >;
    TransactionRevoked: TypedContractEvent<
      TransactionRevokedEvent.InputTuple,
      TransactionRevokedEvent.OutputTuple,
      TransactionRevokedEvent.OutputObject
    >;

    "TransactionSubmitted(uint256,address,address,uint256,bytes)": TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;
    TransactionSubmitted: TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;

    "VotedAdminChange(address)": TypedContractEvent<
      VotedAdminChangeEvent.InputTuple,
      VotedAdminChangeEvent.OutputTuple,
      VotedAdminChangeEvent.OutputObject
    >;
    VotedAdminChange: TypedContractEvent<
      VotedAdminChangeEvent.InputTuple,
      VotedAdminChangeEvent.OutputTuple,
      VotedAdminChangeEvent.OutputObject
    >;
  };
}
