/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LocalAutomator } from "./LocalAutomator";
export * as factories from "./factories";
export { LocalAutomator__factory } from "./factories/LocalAutomator__factory";
